import { GridState } from 'ag-grid-community';
import { AppDefaultView } from './default-views.types';

/**
 * Common aggregation model for executions grid
 */
const createExecutionsAggregationModel = (
  grossAmountColId: string,
  grossAmountRootColId: string,
): Array<{ colId: string; aggFunc: string }> => [
  { colId: 'executingBroker', aggFunc: 'brokers' },
  { colId: grossAmountColId, aggFunc: 'tradeSum' },
  { colId: 'totalNetProceedsAmount', aggFunc: 'tradeNet' },
  { colId: 'executionPricePerUnit', aggFunc: 'avgExecutedPrice' },
  { colId: 'executionQuantity', aggFunc: 'sum' },
  { colId: grossAmountRootColId, aggFunc: 'sum' },
  { colId: 'totalNetProceedsAmountRoot', aggFunc: 'tradeNetUSD' },
  { colId: 'cancelReasonCode', aggFunc: 'aggregateUniqueValues' },
  { colId: 'cancelledByPersonIdSource', aggFunc: 'aggregateUniqueValues' },
];

/**
 * Mapping of appName to default view configuration
 */
export const appDefaultViewsMap: Record<string, AppDefaultView> = {
  // eslint-disable-next-line @typescript-eslint/naming-convention
  'EQTEXECUTIONSACTIVITYUI:EXECUTIONS': {
    appName: 'Block Executions',
    viewName: 'Default Block View',
    description: 'Default view for Block Executions with predefined columns',
    gridState: {
      sideBar: {
        visible: true,
        position: 'right',
        openToolPanel: null,
        toolPanels: {
          columns: { expandedGroupIds: [] },
          filters: { expandedGroupIds: [], expandedColIds: [] },
        },
      },
      columnOrder: {
        orderedColIds: [
          'checkbox',
          'allocations',
          'fmrTickerSymbol',
          'asTradedIvLongName',
          'executionStatusCode',
          'side',
          'executingBroker',
          'executionTraderInitials',
          'fmrMarketExchangeCode',
          'ivTypeCode',
          'executionQuantity',
          'executionPricePerUnit',
          'executionCurrencyCode',
          'executionGrossAmount',
          'executionGrossRootCurrencyAmount',
          'totalNetProceedsAmount',
          'totalNetProceedsAmountRoot',
          'tradeDate',
          'settlementDate',
          'sector',
          'majorIndustry',
          'minorIndustry',
          'underlierFmrIssCusip',
          'underlierLongName',
          'underlierTicker',
          'executionDate',
          'tradingTeam',
          'commissionRate',
          'totalCommissionAmount',
          'totalFeeAmount',
          'traderNote',
          'totalInterestBoughtSoldAmount',
          'commissionTypeCode',
          'totalTaxAmount',
          'cancelAdjustIndicator',
          'cancelTimeStamp',
          'cancelReasonCode',
          'cancelledByPersonIdSource',
          'tradingDesk',
          'specificationValue',
          'fmrIssueCusip',
          'clearingBroker',
          'executingBrokerAmt',
          'exchangeFee',
          'blockPremium',
          'rollRebate',
          'giveUpFee',
          'executionId',
          'limitPriceAmount',
          'foreignExchangeRate',
          'executionClearingBrokerRate',
          'executingBrokerRate',
          'executionBlockPremiumRate',
          'rollRebateRate',
          'giveUpFeeRate',
          'blockId',
          'asExecutedTraderInitials',
          'dealTypeCode',
          'interfundRationaleCode',
          'interfundMessage',
          'executionCommissionAmount',
          'executionCommissionRate',
          'researchCommissionAmount',
          'researchCommissionRate',
          'executionExchangeFeeRate',
          'allocationMethodCode',
          'allocationOverrideReasonCode',
          'allocationOverrideReasonText',
          'cancelRebookExecutionId',
          'parentExecutionId',
          'programCode',
          'isoMarketExchangeCode',
          'recordVersionNumber',
        ],
      },
      columnSizing: {
        columnSizingModel: [
          { colId: 'checkbox', flex: 1, width: 30 },
          { colId: 'allocations', width: 50 },
          { colId: 'fmrTickerSymbol', flex: 1, width: 80 },
          { colId: 'asTradedIvLongName', flex: 1, width: 120 },
          { colId: 'executionStatusCode', flex: 1, width: 120 },
          { colId: 'side', flex: 1, width: 80 },
          { colId: 'executingBroker', flex: 1, width: 80 },
          { colId: 'executionTraderInitials', flex: 1, width: 80 },
          { colId: 'fmrMarketExchangeCode', flex: 1, width: 120 },
          { colId: 'ivTypeCode', flex: 1, width: 120 },
          { colId: 'executionQuantity', flex: 1, width: 80 },
          { colId: 'executionPricePerUnit', flex: 1, width: 80 },
          { colId: 'executionCurrencyCode', flex: 1, width: 80 },
          { colId: 'executionGrossAmount', flex: 1, width: 120 },
          { colId: 'executionGrossRootCurrencyAmount', flex: 1, width: 140 },
          { colId: 'totalNetProceedsAmount', flex: 1, width: 80 },
          { colId: 'totalNetProceedsAmountRoot', flex: 1, width: 140 },
          { colId: 'tradeDate', flex: 1, width: 100 },
          { colId: 'settlementDate', flex: 1, width: 100 },
          { colId: 'sector', flex: 1, width: 120 },
          { colId: 'majorIndustry', flex: 1, width: 120 },
          { colId: 'minorIndustry', flex: 1, width: 120 },
          { colId: 'underlierFmrIssCusip', flex: 1, width: 120 },
          { colId: 'underlierLongName', flex: 1, width: 120 },
          { colId: 'underlierTicker', flex: 1, width: 120 },
          { colId: 'executionDate', flex: 1, width: 100 },
          { colId: 'tradingTeam', flex: 1, width: 120 },
          { colId: 'commissionRate', flex: 1, width: 120 },
          { colId: 'totalCommissionAmount', flex: 1, width: 100 },
          { colId: 'totalFeeAmount', flex: 1, width: 80 },
          { colId: 'traderNote', flex: 1, width: 100 },
          { colId: 'totalInterestBoughtSoldAmount', flex: 1, width: 80 },
          { colId: 'commissionTypeCode', flex: 1, width: 140 },
          { colId: 'totalTaxAmount', flex: 1, width: 80 },
          { colId: 'cancelAdjustIndicator', flex: 1, width: 120 },
          { colId: 'cancelTimeStamp', flex: 1, width: 100 },
          { colId: 'cancelReasonCode', flex: 1, width: 120 },
          { colId: 'cancelledByPersonIdSource', flex: 1, width: 120 },
          { colId: 'tradingDesk', flex: 1, width: 120 },
          { colId: 'specificationValue', flex: 1, width: 120 },
          { colId: 'fmrIssueCusip', flex: 1, width: 120 },
          { colId: 'clearingBroker', flex: 1, width: 150 },
          { colId: 'executingBrokerAmt', flex: 1, width: 150 },
          { colId: 'exchangeFee', flex: 1, width: 120 },
          { colId: 'blockPremium', flex: 1, width: 120 },
          { colId: 'rollRebate', flex: 1, width: 120 },
          { colId: 'giveUpFee', flex: 1, width: 120 },
          { colId: 'executionId', width: 200 },
          { colId: 'limitPriceAmount', width: 200 },
          { colId: 'foreignExchangeRate', width: 200 },
          { colId: 'executionClearingBrokerRate', width: 200 },
          { colId: 'executingBrokerRate', width: 200 },
          { colId: 'executionBlockPremiumRate', width: 200 },
          { colId: 'rollRebateRate', width: 200 },
          { colId: 'giveUpFeeRate', width: 200 },
          { colId: 'blockId', width: 200 },
          { colId: 'asExecutedTraderInitials', width: 200 },
          { colId: 'dealTypeCode', width: 200 },
          { colId: 'interfundRationaleCode', width: 200 },
          { colId: 'interfundMessage', width: 200 },
          { colId: 'executionCommissionAmount', width: 200 },
          { colId: 'executionCommissionRate', width: 200 },
          { colId: 'researchCommissionAmount', width: 200 },
          { colId: 'researchCommissionRate', width: 200 },
          { colId: 'executionExchangeFeeRate', width: 200 },
          { colId: 'allocationMethodCode', width: 200 },
          { colId: 'allocationOverrideReasonCode', width: 200 },
          { colId: 'allocationOverrideReasonText', width: 200 },
          { colId: 'cancelRebookExecutionId', width: 200 },
          { colId: 'parentExecutionId', width: 200 },
          { colId: 'programCode', width: 200 },
          { colId: 'isoMarketExchangeCode', width: 200 },
          { colId: 'recordVersionNumber', width: 200 },
        ],
      },
      columnVisibility: {
        hiddenColIds: [
          'commissionRate',
          'totalCommissionAmount',
          'totalFeeAmount',
          'traderNote',
          'totalInterestBoughtSoldAmount',
          'commissionTypeCode',
          'totalTaxAmount',
          'cancelAdjustIndicator',
          'cancelTimeStamp',
          'cancelReasonCode',
          'cancelledByPersonIdSource',
          'tradingDesk',
          'specificationValue',
          'fmrIssueCusip',
          'clearingBroker',
          'executingBrokerAmt',
          'exchangeFee',
          'blockPremium',
          'rollRebate',
          'giveUpFee',
          'executionId',
          'limitPriceAmount',
          'foreignExchangeRate',
          'executionClearingBrokerRate',
          'executingBrokerRate',
          'executionBlockPremiumRate',
          'rollRebateRate',
          'giveUpFeeRate',
          'blockId',
          'asExecutedTraderInitials',
          'dealTypeCode',
          'interfundRationaleCode',
          'interfundMessage',
          'executionCommissionAmount',
          'executionCommissionRate',
          'researchCommissionAmount',
          'researchCommissionRate',
          'executionExchangeFeeRate',
          'allocationMethodCode',
          'allocationOverrideReasonCode',
          'allocationOverrideReasonText',
          'cancelRebookExecutionId',
          'parentExecutionId',
          'programCode',
          'isoMarketExchangeCode',
          'recordVersionNumber',
        ],
      },
      expandAll: false,
      sort: { sortModel: [] },
      aggregation: {
        aggregationModel: createExecutionsAggregationModel(
          'executionGrossAmount',
          'executionGrossRootCurrencyAmount',
        ),
      },
      filter: { filterModel: {} },
      pivot: {
        pivotMode: false,
        pivotColIds: [],
      },
      columnPinning: {
        leftColIds: [],
        rightColIds: [],
      },
      pagination: { page: 0 },
      columnGroup: { openColumnGroupIds: [] },
      rowGroup: { groupColIds: [] },
      rowGroupExpansion: { expandedRowGroupIds: [] },
      rangeSelection: { cellRanges: [] },
      scroll: { top: 0, left: 0 },
      rowSelection: [],
    } as GridState,
  },
  // eslint-disable-next-line @typescript-eslint/naming-convention
  'EQTEXECUTIONSACTIVITYUI:TRADES': {
    appName: 'Fund Executions',
    viewName: 'Default Fund View',
    description: 'Default view for Fund Executions with predefined columns',
    gridState: {
      sideBar: {
        visible: true,
        position: 'right',
        openToolPanel: null,
        toolPanels: {
          columns: { expandedGroupIds: [] },
          filters: { expandedGroupIds: [], expandedColIds: [] },
        },
      },
      columnOrder: {
        orderedColIds: [
          'fmrTickerSymbol',
          'asTradedIvLongName',
          'tradeStatus',
          'side',
          'enteredFundShortName',
          'executingBroker',
          'asExecutedTraderInitials',
          'fmrMarketExchangeCode',
          'ivTypCD',
          'executionQuantity',
          'executionPricePerUnit',
          'executionCurrencyCode',
          'tradeGrossAmount',
          'tradeGrossAmountRootCurrency',
          'totalNetProceedsAmount',
          'totalNetProceedsAmountRoot',
          'tradeDate',
          'settlementDate',
          'sector',
          'majorIndustry',
          'minorIndustry',
          'underlierFmrIssCusip',
          'underlierLongName',
          'underlierTicker',
          'creationTimestamp',
          'tradingTeamShortName',
        ],
      },
      columnSizing: {
        columnSizingModel: [
          { colId: 'fmrTickerSymbol', flex: 1, width: 120 },
          { colId: 'asTradedIvLongName', flex: 1, width: 180 },
          { colId: 'tradeStatus', flex: 1, width: 120 },
          { colId: 'side', flex: 1, width: 100 },
          { colId: 'enteredFundShortName', flex: 1, width: 120 },
          { colId: 'executingBroker', flex: 1, width: 120 },
          { colId: 'asExecutedTraderInitials', flex: 1, width: 120 },
          { colId: 'fmrMarketExchangeCode', flex: 1, width: 150 },
          { colId: 'ivTypCD', flex: 1, width: 140 },
          { colId: 'executionQuantity', flex: 1, width: 150 },
          { colId: 'executionPricePerUnit', flex: 1, width: 130 },
          { colId: 'executionCurrencyCode', flex: 1, width: 100 },
          { colId: 'tradeGrossAmount', flex: 1, width: 130 },
          { colId: 'tradeGrossAmountRootCurrency', flex: 1, width: 150 },
          { colId: 'totalNetProceedsAmount', flex: 1, width: 130 },
          { colId: 'totalNetProceedsAmountRoot', flex: 1, width: 150 },
          { colId: 'tradeDate', flex: 1, width: 120 },
          { colId: 'settlementDate', flex: 1, width: 120 },
          { colId: 'sector', flex: 1, width: 120 },
          { colId: 'majorIndustry', flex: 1, width: 150 },
          { colId: 'minorIndustry', flex: 1, width: 150 },
          { colId: 'underlierFmrIssCusip', flex: 1, width: 150 },
          { colId: 'underlierLongName', flex: 1, width: 200 },
          { colId: 'underlierTicker', flex: 1, width: 150 },
          { colId: 'creationTimestamp', flex: 1, width: 170 },
          { colId: 'tradingTeamShortName', flex: 1, width: 140 },
        ],
      },
      columnVisibility: {
        hiddenColIds: [
          'checkbox',
          'allocations',
          'entityId',
          'traderNote',
          'totalCommissionAmount',
          'commissionRate',
          'commissionTypeCode',
          'totalFeeAmount',
          'totalInterestBoughtSoldAmount',
          'totalTaxAmount',
          'cancelAdjustIndicator',
          'cancelTimeStamp',
          'cancelReasonCode',
          'cancelledByPersonIdSource',
          'tradingDesk',
          'underlyingSymbol',
          'specificationValue',
          'trdTypCD',
          'execId',
          'limitPrcAmt',
          'fxRt',
          'fmrIssueCusip',
          'derivativeComm',
          'clearingBroker',
          'executingBrokerAmt',
          'exchangeFee',
          'blockPremium',
          'rollRebate',
          'giveUpFee',
        ],
      },
      expandAll: false,
      sort: { sortModel: [] },
      aggregation: {
        aggregationModel: createExecutionsAggregationModel(
          'tradeGrossAmount',
          'tradeGrossAmountRootCurrency',
        ),
      },
      filter: { filterModel: {} },
      pivot: {
        pivotMode: false,
        pivotColIds: [],
      },
      columnPinning: {
        leftColIds: [],
        rightColIds: [],
      },
      pagination: { page: 0 },
      columnGroup: { openColumnGroupIds: [] },
      rowGroup: { groupColIds: [] },
      rowGroupExpansion: { expandedRowGroupIds: [] },
      rangeSelection: { cellRanges: [] },
      scroll: { top: 0, left: 0 },
      rowSelection: [],
    } as GridState,
  },
};
