import {
  ColDef,
  ICellRendererParams,
  ValueFormatterParams,
} from 'ag-grid-community';
import { getDateTimeGetter, numberFormatter } from '@trade-platform/shared/data-access';
import { AllocationModel } from '@trade-platform/exac/shared/data';
import { booleanColumnDisplayColumnDef } from './shared-definition-options';

/* eslint-disable */
export const allocationsColumnDefs: ColDef<AllocationModel>[] = [
  {
    headerName: 'Status',
    field: 'tradeStatus',
    colId: 'tradeStatus',
    minWidth: 80,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Fund',
    field: 'enteredFundShortName',
    colId: 'enteredFundShortName',
    minWidth: 80,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Trade Quantity',
    field: 'tradeQuantity',
    colId: 'tradeQuantity',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Limit Price',
    field: 'limitPriceAmount',
    colId: 'limitPriceAmount',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 6),
  },
  {
    headerName: 'Gross Amount',
    field: 'tradeGrossAmount',
    colId: 'tradeGrossAmount',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    valueGetter: (params: any) => {
      if (params.node != null && !params.node.group) {
        return {
          currency: params.data?.executionCurrencyCode as string,
          side: params.data?.side as string,
          amount: (params.data?.tradeGrossAmount as number) ?? 0,
        };
      } else return null;
    },
    valueFormatter: (params: ValueFormatterParams) =>
      numberFormatter(
        { value: params.value?.amount as number } as ICellRendererParams,
        2,
      ),
    keyCreator: (params) => params.value?.amount as string,
    filterValueGetter: (params) => params.data?.tradeGrossAmount as number,
  },
  {
    headerName: 'Gross Amount USD',
    field: 'tradeGrossAmountRootCurrency',
    colId: 'tradeGrossAmountRootCurrency',
    minWidth: 140,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Taxes',
    field: 'totalTaxAmount',
    colId: 'totalTaxAmount',
    minWidth: 80,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Fees',
    field: 'totalFeeAmount',
    colId: 'totalFeeAmount',
    minWidth: 80,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Interest',
    field: 'totalInterestBoughtSoldAmount',
    colId: 'totalInterestBoughtSoldAmount',
    minWidth: 80,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Cancel Date/Time',
    field: 'cancelTimeStamp',
    colId: 'cancelTimeStamp',
    minWidth: 140,
    filter: 'agDateColumnFilter',
    valueFormatter: (params) => {
      if (params.data !== undefined) {
        return (
          getDateTimeGetter(<string>params.data?.cancelTimeStamp?.toString()) ?? ''
        );
      } else {
        return '';
      }
    },
  },
  {
    headerName: 'Cancel Reason',
    field: 'cancelReasonCode',
    colId: 'cancelReasonCode',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Trader Note',
    field: 'traderNote',
    colId: 'traderNote',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Ticket ID',
    field: 'ticketId',
    colId: 'ticketId',
    minWidth: 100,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Parent Trade ID',
    field: 'parentTradeId',
    colId: 'parentTradeId',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Rebook Trade ID',
    field: 'rebookTradeId',
    colId: 'rebookTradeId',
    minWidth: 100,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'First Trade ID',
    field: 'firstTradeId',
    colId: 'firstTradeId',
    minWidth: 100,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Order Quantity',
    field: 'blockOrderQuantity',
    colId: 'blockOrderQuantity',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Order Creation Date/Time',
    field: 'orderCreationDateTime',
    colId: 'orderCreationDateTime',
    minWidth: 140,
    filter: 'agDateColumnFilter',
    valueFormatter: (params) => {
      if (params.data !== undefined) {
        return getDateTimeGetter(<string>params.data?.orderCreationDateTime?.toString());
      } else {
        return '';
      }
    },
  },
  {
    headerName: 'Final Allocation Quantity',
    field: 'finalAllocationQuantity',
    colId: 'finalAllocationQuantity',
    minWidth: 140,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'System Allocation Quantity',
    field: 'systemAllocationQuantity',
    colId: 'systemAllocationQuantity',
    minWidth: 140,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Trader Directed Quantity',
    field: 'directedQuantity',
    colId: 'directedQuantity',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Default Weight',
    field: 'defaultWeight',
    colId: 'defaultWeight',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Weight Override',
    field: 'weightOverride',
    colId: 'weightOverride',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Holdings Quantity',
    field: 'holdingsQuantity',
    colId: 'holdingsQuantity',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Shares in Escrow',
    field: 'sharesInEscrow',
    colId: 'sharesInEscrow',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Board Lot',
    field: 'boardLot',
    colId: 'boardLot',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Minimum Allocation Amount',
    field: 'minAllocationAmount',
    colId: 'minAllocationAmount',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Minimum Allocation Quantity',
    field: 'minAllocationShares',
    colId: 'minAllocationShares',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Fund Assets',
    field: 'fundAssetsUSD',
    colId: 'fundAssetsUSD',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Adjusted Fund Assets',
    field: 'adjustedAssets',
    colId: 'adjustedAssets',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Allocation Reason Code',
    field: 'allocationReasonCode',
    colId: 'allocationReasonCode',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Manual Allocation',
    field: 'manualAllocation',
    colId: 'manualAllocation',
    minWidth: 120,
    filter: 'agSetColumnFilter',
    ...booleanColumnDisplayColumnDef,
  },
  {
    headerName: 'Alert Code',
    field: 'autexCode',
    colId: 'autexCode',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Trade ID',
    field: 'tradeId',
    colId: 'tradeId',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Trade Type',
    field: 'tradeTypeCode',
    colId: 'tradeTypeCode',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Net Amount',
    field: 'totalNetProceedsAmount',
    colId: 'totalNetProceedsAmount',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Net Amount USD',
    field: 'totalNetProceedsAmountRoot',
    colId: 'totalNetProceedsAmountRoot',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Pilot Fund Indicator',
    field: 'pilotIndicator',
    colId: 'pilotIndicator',
    minWidth: 120,
    filter: 'agSetColumnFilter',
    ...booleanColumnDisplayColumnDef,
  },
  {
    headerName: 'Working Currency Code',
    field: 'workingCurrencyCode',
    colId: 'workingCurrencyCode',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Symbol',
    field: 'fmrTickerSymbol',
    colId: 'fmrTickerSymbol',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Security Name',
    field: 'asTradedIvLongName',
    colId: 'asTradedIvLongName',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Commission Type',
    field: 'commissionTypeCode',
    colId: 'commissionTypeCode',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Cancel/Rebook Indicator',
    field: 'cancelAdjustIndicator',
    colId: 'cancelAdjustIndicator',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Cancelled By',
    field: 'cancelledByPersonName',
    colId: 'cancelledByPersonName',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Broker',
    field: 'executingBroker',
    colId: 'executingBroker',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Currency',
    field: 'executionCurrencyCode',
    colId: 'executionCurrencyCode',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Executed Price',
    field: 'executionPricePerUnit',
    colId: 'executionPricePerUnit',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Trader',
    field: 'executionTraderInitials',
    colId: 'executionTraderInitials',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Market/Exchange Code',
    field: 'fmrMarketExchangeCode',
    colId: 'fmrMarketExchangeCode',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Side',
    field: 'side',
    colId: 'side',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Settle Date',
    field: 'settlementDate',
    colId: 'settlementDate',
    minWidth: 120,
    filter: 'agDateColumnFilter',
  },
  {
    headerName: 'Trade Date',
    field: 'tradeDate',
    colId: 'tradeDate',
    minWidth: 120,
    filter: 'agDateColumnFilter',
  },
  {
    headerName: 'Trading Desk',
    field: 'tradingDesk',
    colId: 'tradingDesk',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Trading Team',
    field: 'tradingTeamShortName',
    colId: 'tradingTeamShortName',
    minWidth: 120,
    filter: 'agSetColumnFilter',
  },
  {
    headerName: 'Commission Rate',
    field: 'commissionRate',
    colId: 'commissionRate',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Commission',
    field: 'totalCommissionAmount',
    colId: 'totalCommissionAmount',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Execution Commission Rate',
    field: 'executionCommissionRate',
    colId: 'executionCommissionRate',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Execution Commission Amount',
    field: 'executionCommissionAmount',
    colId: 'executionCommissionAmount',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Research Commission Rate',
    field: 'researchCommissionRate',
    colId: 'researchCommissionRate',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Research Commission Amount',
    field: 'researchCommissionAmount',
    colId: 'researchCommissionAmount',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Clearing Broker Commission Rate',
    field: 'executionClearingBrokerRate',
    colId: 'executionClearingBrokerRate',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Clearing Broker Commission Amount',
    field: 'clearingBrokerAmt',
    colId: 'clearingBrokerAmt',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Executing Broker Commission Rate',
    field: 'executingBrokerRate',
    colId: 'executingBrokerRate',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Executing Broker Commission Amount',
    field: 'executingBrokerAmt',
    colId: 'executingBrokerAmt',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Exchange Fee Rate',
    field: 'executionExchangeFeeRate',
    colId: 'executionExchangeFeeRate',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Exchange Fee Amount',
    field: 'exchangeFee',
    colId: 'exchangeFee',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Block Premium Rate',
    field: 'executionBlockPremiumRate',
    colId: 'executionBlockPremiumRate',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Block Premium Amount',
    field: 'blockPremium',
    colId: 'blockPremium',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Roll Rebate Rate',
    field: 'rollRebateRate',
    colId: 'rollRebateRate',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Roll Rebate Amount',
    field: 'rollRebate',
    colId: 'rollRebate',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Give Up/In Fee Rate',
    field: 'giveUpFeeRate',
    colId: 'giveUpFeeRate',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
  {
    headerName: 'Give Up/In Fee Amount',
    field: 'giveUpFee',
    colId: 'giveUpFee',
    minWidth: 120,
    filter: 'agNumberColumnFilter',
    cellRenderer: (params: ICellRendererParams) => numberFormatter(params, 2),
  },
];
